### ISSUE TITLE
File list not updating

### ISSUE THREAD

**Issue by lmshiry** [ssahara/dokuwiki-plugin-medialist#14]
Hi,

I have noticed that the file list does not update most of the time until I edit and re-save the dokuwiki page where this plugin is used.

Thanks,
Lee

**Comment by ssahara** [comment]
How about combination with [control macro](https://www.dokuwiki.org/wiki:syntax#control_macros) `~~NOCACHE~~`?

**Comment by lmshiry** [comment]
Thanks! That seems to work!
